---
title: "R Notebook"
output: html_notebook
---

```{r}
options(warn=-1) # ignore warns
require(GGally, quietly = TRUE)
require(reshape2, quietly = TRUE)
require(tidyverse, quietly = TRUE, warn.conflicts = FALSE)
library(ggfortify)
library(cluster)
library(broom)
library(tidyverse)
library(plotly)
library(resample)
library(lubridate)
library(ggpubr)
library(here)
library(highcharter)
library(mongolite)

HOST_IP = "mongodb://192.168.1.8:27017/news_2018"
```

```{r}
carta_capital <- mongo("carta_capital", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
el_pais <- mongo("el_pais", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
estadao <- mongo("estadao", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
folha <- mongo("folha", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
#gazeta_do_povo <- mongo("gazeta_do_povo", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
oantagonista <- mongo("oantagonista", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
oglobo <- mongo("oglobo", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
veja <- mongo("veja", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)

carta_capital$date <- as.numeric(as.character(carta_capital$date))
el_pais$date <- as.numeric(as.character(el_pais$date))
estadao$date <- as.numeric(as.character(estadao$date))
folha$date <- as.numeric(as.character(folha$date))
#gazeta_do_povo$date <- as.numeric(as.character(gazeta_do_povo$date))
oantagonista$date <- as.numeric(as.character(oantagonista$date))
oglobo$date <- as.numeric(as.character(oglobo$date))
veja$date <- as.numeric(as.character(veja$date))

el_pais[el_pais == "internacional"]<-"politica"
oglobo[oglobo == "internacional"]<-"politica"
oglobo[oglobo == "economia"]<-"esporte"
oantagonista[oantagonista == "diversos"]<-"politica"
oantagonista[oantagonista == "tecnologia"]<-"esporte"


news <-bind_rows(
    "Carta Capital" = carta_capital,
    "El País" = el_pais,
    "Estadão" = estadao, 
    "Folha de SP" = folha, 
    #"gazeta_do_povo" = gazeta_do_povo,
    "O Antagonista" = oantagonista,
    "O Globo" = oglobo,
    "Veja" = veja,
    .id = "jornal")
```

```{r}
bias_section <- news %>%
  filter(section %in% c("politica", "esporte")) %>%
  mutate(
    dateFormat = as.Date(as_datetime(as.numeric(date))),
    month = months(as.Date(as_datetime(as.numeric(date))))) %>%
  group_by(month, section, jornal, dateFormat) %>%
  summarise(bias = (1 - (mean(arg) + mean(sen) + mean(val) + mean(pre) + mean(mod)) / 5) * 100)
```

```{r}
ggplot(bias_section, aes(x = reorder(month, dateFormat), y = bias, fill = section)) + 
  geom_bar(stat="identity") + #position = 'dodge' 
  labs(y= "average subjectivity", x = "month") +
  theme_bw() +
  theme(#legend.position="none", 
        axis.text=element_text(size=15),
        plot.title = element_text(size=22)) +
  facet_wrap(~jornal, ncol = 1)
ggsave("fig7.pdf", width = 12, height = 20)
```

