---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
options(warn=-1) # ignore warns
require(GGally, quietly = TRUE)
require(reshape2, quietly = TRUE)
require(tidyverse, quietly = TRUE, warn.conflicts = FALSE)
library(ggfortify)
library(cluster)
library(broom)
library(tidyverse)
library(plotly)
library(resample)
library(lubridate)
library(ggpubr)
library(here)
library(highcharter)
library(mongolite)

HOST_IP = "mongodb://192.168.1.6:27017/news_2018"
```

## Corregando dados

```{r message=FALSE, warning=FALSE}
carta_capital <- mongo("carta_capital", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
el_pais <- mongo("el_pais", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
estadao <- mongo("estadao", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
folha <- mongo("folha", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
#gazeta_do_povo <- mongo("gazeta_do_povo", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
oantagonista <- mongo("oantagonista", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
oglobo <- mongo("oglobo", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)
veja <- mongo("veja", url = HOST_IP)$find() %>% filter(arg >= 0, sen >= 0, val >= 0, pre >= 0, mod >= 0)

carta_capital$date <- as.numeric(as.character(carta_capital$date))
el_pais$date <- as.numeric(as.character(el_pais$date))
estadao$date <- as.numeric(as.character(estadao$date))
folha$date <- as.numeric(as.character(folha$date))
#gazeta_do_povo$date <- as.numeric(as.character(gazeta_do_povo$date))
oantagonista$date <- as.numeric(as.character(oantagonista$date))
oglobo$date <- as.numeric(as.character(oglobo$date))
veja$date <- as.numeric(as.character(veja$date))


el_pais[el_pais == "internacional"]<-"politica"
oglobo[oglobo == "internacional"]<-"politica"
oglobo[oglobo == "economia"]<-"esporte"
oantagonista[oantagonista == "diversos"]<-"politica"
oantagonista[oantagonista == "tecnologia"]<-"esporte"


esporte <-bind_rows(
    "Carta Capital" = carta_capital %>% filter(section == 'esporte'),
    "El País" = el_pais %>% filter(section == 'esporte'),
    "Estadão" = estadao %>% filter(section =='esporte'), 
    "Folha de SP" = folha %>% filter(section == 'esporte'), 
    #"gazeta_do_povo" = gazeta_do_povo,
    "O Antagonista" = oantagonista %>% filter(section == 'esporte'),
    "O Globo" = oglobo %>% filter(section == 'esporte'),
    "Veja" = veja %>% filter(section == 'esporte'),
    .id = "jornal")

politica <-bind_rows(
    "Carta Capital" = carta_capital %>% filter(section == 'politica'),
    "El País" = el_pais %>% filter(section == 'politica'),
    "Estadão" = estadao %>% filter(section =='politica'), 
    "Folha de SP" = folha %>% filter(section == 'politica'), 
    #"gazeta_do_povo" = gazeta_do_povo,
    "O Antagonista" = oantagonista %>% filter(section == 'politica'),
    "O Globo" = oglobo %>% filter(section == 'politica'),
    "Veja" = veja %>% filter(section == 'politica'),
    .id = "jornal")
```


```{r}
library(Hmisc)
describe(pop %>% select(type_news))
```


## Política

```{r}
set.seed(1212)

repeticoes = 5000 # pelo menos 2000, mas mais não faz mal.

um_bootstrap <- function(x){
  election_news <- x %>% filter(type_news == 'election') %>% pull(bias_news)
  boot_election_news <- sample(election_news,           # amostre dos dados
                   size = NROW(election_news), # tamanho igual ao recebido
                   replace = TRUE) # aqui é o bootstrap
  
  non_election_news <- x %>% filter(type_news == 'non_election') %>% pull(bias_news)
  boot_non_election_news <- sample(non_election_news,           # amostre dos dados
                   size = NROW(non_election_news), # tamanho igual ao recebido
                   replace = TRUE) # aqui é o bootstrap
  
  return(mean(boot_non_election_news) - mean(boot_election_news))
}

# definindo portal para população 
pop <- politica %>% 
  mutate(bias_news = (1 - (arg + sen + val + pre + mod) / 5)) %>% 
  mutate(type_news = ifelse(grepl("eleiç", tolower(text)), "election", "non_election")) %>% 
  filter(!is.na(type_news))

theta_c = pop %>% group_by(type_news) %>% 
        summarise(media = mean(bias_news))

theta_c = theta_c %>% filter(type_news == "election") %>% pull(media) - theta_c %>% filter(type_news == "non_election") %>% pull(media)

# A REAMOSTRAGEM
reamostragens = tibble(i = 1:repeticoes) %>% 
  mutate(theta_c_s = map_dbl(i, ~ um_bootstrap(pop)))

ci_politica = reamostragens %>% 
  summarise(conf.low = theta_c + quantile((theta_c_s - theta_c), .05), 
         conf.high = theta_c + quantile((theta_c_s - theta_c), .95), 
         statistic = theta_c)

```

# Esporte
```{r}
set.seed(1212)

repeticoes = 5000 # pelo menos 2000, mas mais não faz mal.

um_bootstrap <- function(x){
  copa_news <- x %>% filter(type_news == 'copa') %>% pull(bias_news)
  boot_copa_news <- sample(copa_news,           # amostre dos dados
                   size = NROW(copa_news), # tamanho igual ao recebido
                   replace = TRUE) # aqui é o bootstrap
  
  non_copa_news <- x %>% filter(type_news == 'non_copa') %>% pull(bias_news)
  boot_non_copa_news <- sample(non_copa_news,           # amostre dos dados
                   size = NROW(non_copa_news), # tamanho igual ao recebido
                   replace = TRUE) # aqui é o bootstrap
  
  return( mean(boot_non_copa_news) - mean(boot_copa_news))
}
# definindo portal para população 
pop <- esporte %>% 
  mutate(bias_news = (1 - (arg + sen + val + pre + mod) / 5)) %>% 
  mutate(type_news = ifelse(grepl("copa", tolower(text)), "copa", "non_copa")) %>% 
  filter(!is.na(type_news))

theta_c = pop %>% group_by(type_news) %>% 
        summarise(media = mean(bias_news))

theta_c = theta_c %>% filter(type_news == "copa") %>% pull(media) - theta_c %>% filter(type_news == "non_copa") %>% pull(media)

# A REAMOSTRAGEM
reamostragens = tibble(i = 1:repeticoes) %>% 
  mutate(theta_c_s = map_dbl(i, ~ um_bootstrap(pop)))

ci_esporte = reamostragens %>% 
  summarise(conf.low = theta_c + quantile((theta_c_s - theta_c), .05), 
         conf.high = theta_c + quantile((theta_c_s - theta_c), .95), 
         statistic = theta_c)

ci_events = data.frame(rbind(ci_politica, ci_esporte))

ci_events$section = c("Politics", "Sport")

```



```{r}
secplot <- ci_events %>% 
  ggplot(aes(x = section, ymin = conf.low, ymax = conf.high, color = section)) + 
  geom_errorbar(width = .8, size=.8) +
  labs(#title = "Diferença média de subjetividade",
#       subtitle = "Estimativa da diferença média entre notícias opinativas e informativas",
       x = "", 
       y = "") +
  scale_y_continuous(labels = scales::percent) +
  theme(legend.position = "none") +
  theme_bw() +
  theme_bw() +
  theme(legend.position="none", 
        axis.text=element_text(size=20),
        plot.title = element_text(size=22)
        )

secplot

ggsave("fig6.pdf", width = 8, height = 6)
```

